from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import numpy as np

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 701)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top.sizePolicy().hasHeightForWidth())
        self.frame_top.setSizePolicy(sizePolicy)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(18)
        self.frame_top.setFont(font)
        self.frame_top.setObjectName("frame_top")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_top)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_top = QtWidgets.QLabel(self.frame_top)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        self.label_top.setFont(font)
        self.label_top.setObjectName("label_top")
        self.verticalLayout_2.addWidget(self.label_top)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame_center = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_center.sizePolicy().hasHeightForWidth())
        self.frame_center.setSizePolicy(sizePolicy)
        self.frame_center.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_center.setStyleSheet("background-color: yellow;  ")
        self.frame_center.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_center.setObjectName("frame_center")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_center)
        self.gridLayout.setObjectName("gridLayout")
        self.label_c = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_c.setFont(font)
        self.label_c.setStyleSheet("")
        self.label_c.setAlignment(QtCore.Qt.AlignCenter)
        self.label_c.setObjectName("label_c")
        self.gridLayout.addWidget(self.label_c, 0, 0, 1, 1)
        self.label_c5 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_c5.setFont(font)
        self.label_c5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_c5.setObjectName("label_c5")
        self.gridLayout.addWidget(self.label_c5, 5, 0, 1, 1)
        self.label_a4 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_a4.setFont(font)
        self.label_a4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a4.setObjectName("label_a4")
        self.gridLayout.addWidget(self.label_a4, 4, 1, 1, 1)
        self.label_q5 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_q5.setFont(font)
        self.label_q5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q5.setObjectName("label_q5")
        self.gridLayout.addWidget(self.label_q5, 5, 2, 1, 1)
        self.label_q4 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_q4.setFont(font)
        self.label_q4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q4.setObjectName("label_q4")
        self.gridLayout.addWidget(self.label_q4, 4, 2, 1, 1)
        self.label_m2 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_m2.setFont(font)
        self.label_m2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_m2.setObjectName("label_m2")
        self.gridLayout.addWidget(self.label_m2, 2, 3, 1, 1)
        self.label_state1 = QtWidgets.QLabel(self.frame_center)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_state1.sizePolicy().hasHeightForWidth())
        self.label_state1.setSizePolicy(sizePolicy)
        self.label_state1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_state1.setFont(font)
        self.label_state1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state1.setObjectName("label_state1")
        self.gridLayout.addWidget(self.label_state1, 1, 4, 1, 1)
        self.label_cycle1 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_cycle1.setFont(font)
        self.label_cycle1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cycle1.setObjectName("label_cycle1")
        self.gridLayout.addWidget(self.label_cycle1, 1, 5, 1, 1)
        self.label_m5 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_m5.setFont(font)
        self.label_m5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_m5.setObjectName("label_m5")
        self.gridLayout.addWidget(self.label_m5, 5, 3, 1, 1)
        self.label_c4 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_c4.setFont(font)
        self.label_c4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_c4.setObjectName("label_c4")
        self.gridLayout.addWidget(self.label_c4, 4, 0, 1, 1)
        self.label_a1 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_a1.setFont(font)
        self.label_a1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a1.setObjectName("label_a1")
        self.gridLayout.addWidget(self.label_a1, 1, 1, 1, 1)
        self.label_state4 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_state4.setFont(font)
        self.label_state4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state4.setObjectName("label_state4")
        self.gridLayout.addWidget(self.label_state4, 4, 4, 1, 1)
        self.label_cycle4 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_cycle4.setFont(font)
        self.label_cycle4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cycle4.setObjectName("label_cycle4")
        self.gridLayout.addWidget(self.label_cycle4, 4, 5, 1, 1)
        self.label_m1 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_m1.setFont(font)
        self.label_m1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_m1.setObjectName("label_m1")
        self.gridLayout.addWidget(self.label_m1, 1, 3, 1, 1)
        self.label_state3 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_state3.setFont(font)
        self.label_state3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state3.setObjectName("label_state3")
        self.gridLayout.addWidget(self.label_state3, 3, 4, 1, 1)
        self.label_c2 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_c2.setFont(font)
        self.label_c2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_c2.setObjectName("label_c2")
        self.gridLayout.addWidget(self.label_c2, 2, 0, 1, 1)
        self.label_cycle3 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_cycle3.setFont(font)
        self.label_cycle3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cycle3.setObjectName("label_cycle3")
        self.gridLayout.addWidget(self.label_cycle3, 3, 5, 1, 1)
        self.label_a2 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_a2.setFont(font)
        self.label_a2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a2.setObjectName("label_a2")
        self.gridLayout.addWidget(self.label_a2, 2, 1, 1, 1)
        self.label_a3 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_a3.setFont(font)
        self.label_a3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a3.setObjectName("label_a3")
        self.gridLayout.addWidget(self.label_a3, 3, 1, 1, 1)
        self.label_q3 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_q3.setFont(font)
        self.label_q3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q3.setObjectName("label_q3")
        self.gridLayout.addWidget(self.label_q3, 3, 2, 1, 1)
        self.label_m3 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_m3.setFont(font)
        self.label_m3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_m3.setObjectName("label_m3")
        self.gridLayout.addWidget(self.label_m3, 3, 3, 1, 1)
        self.label_state5 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_state5.setFont(font)
        self.label_state5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state5.setObjectName("label_state5")
        self.gridLayout.addWidget(self.label_state5, 5, 4, 1, 1)
        self.label_m = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_m.setFont(font)
        self.label_m.setAlignment(QtCore.Qt.AlignCenter)
        self.label_m.setObjectName("label_m")
        self.gridLayout.addWidget(self.label_m, 0, 3, 1, 1)
        self.label_cycle5 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_cycle5.setFont(font)
        self.label_cycle5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cycle5.setObjectName("label_cycle5")
        self.gridLayout.addWidget(self.label_cycle5, 5, 5, 1, 1)
        self.label_q = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_q.setFont(font)
        self.label_q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q.setObjectName("label_q")
        self.gridLayout.addWidget(self.label_q, 0, 2, 1, 1)
        self.label_q1 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_q1.setFont(font)
        self.label_q1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q1.setObjectName("label_q1")
        self.gridLayout.addWidget(self.label_q1, 1, 2, 1, 1)
        self.label_a5 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_a5.setFont(font)
        self.label_a5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a5.setObjectName("label_a5")
        self.gridLayout.addWidget(self.label_a5, 5, 1, 1, 1)
        self.label_q2 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_q2.setFont(font)
        self.label_q2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q2.setObjectName("label_q2")
        self.gridLayout.addWidget(self.label_q2, 2, 2, 1, 1)
        self.label_state = QtWidgets.QLabel(self.frame_center)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_state.sizePolicy().hasHeightForWidth())
        self.label_state.setSizePolicy(sizePolicy)
        self.label_state.setMinimumSize(QtCore.QSize(227, 0))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_state.setFont(font)
        self.label_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state.setObjectName("label_state")
        self.gridLayout.addWidget(self.label_state, 0, 4, 1, 1)
        self.label_m4 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_m4.setFont(font)
        self.label_m4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_m4.setObjectName("label_m4")
        self.gridLayout.addWidget(self.label_m4, 4, 3, 1, 1)
        self.label_c3 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_c3.setFont(font)
        self.label_c3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_c3.setObjectName("label_c3")
        self.gridLayout.addWidget(self.label_c3, 3, 0, 1, 1)
        self.label_state2 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_state2.setFont(font)
        self.label_state2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state2.setObjectName("label_state2")
        self.gridLayout.addWidget(self.label_state2, 2, 4, 1, 1)
        self.label_a = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_a.setFont(font)
        self.label_a.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a.setObjectName("label_a")
        self.gridLayout.addWidget(self.label_a, 0, 1, 1, 1)
        self.label_cycle = QtWidgets.QLabel(self.frame_center)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cycle.sizePolicy().hasHeightForWidth())
        self.label_cycle.setSizePolicy(sizePolicy)
        self.label_cycle.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_cycle.setFont(font)
        self.label_cycle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cycle.setObjectName("label_cycle")
        self.gridLayout.addWidget(self.label_cycle, 0, 5, 1, 1)
        self.label_c1 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_c1.setFont(font)
        self.label_c1.setStyleSheet("")
        self.label_c1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_c1.setObjectName("label_c1")
        self.gridLayout.addWidget(self.label_c1, 1, 0, 1, 1)
        self.label_cycle2 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_cycle2.setFont(font)
        self.label_cycle2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cycle2.setObjectName("label_cycle2")
        self.gridLayout.addWidget(self.label_cycle2, 2, 5, 1, 1)
        self.label_c6 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_c6.setFont(font)
        self.label_c6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_c6.setObjectName("label_c6")
        self.gridLayout.addWidget(self.label_c6, 6, 0, 1, 1)
        self.label_a6 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_a6.setFont(font)
        self.label_a6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a6.setObjectName("label_a6")
        self.gridLayout.addWidget(self.label_a6, 6, 1, 1, 1)
        self.label_q6 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_q6.setFont(font)
        self.label_q6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q6.setObjectName("label_q6")
        self.gridLayout.addWidget(self.label_q6, 6, 2, 1, 1)
        self.label_m6 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_m6.setFont(font)
        self.label_m6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_m6.setObjectName("label_m6")
        self.gridLayout.addWidget(self.label_m6, 6, 3, 1, 1)
        self.label_state6 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_state6.setFont(font)
        self.label_state6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_state6.setObjectName("label_state6")
        self.gridLayout.addWidget(self.label_state6, 6, 4, 1, 1)
        self.label_cycle6 = QtWidgets.QLabel(self.frame_center)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_cycle6.setFont(font)
        self.label_cycle6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cycle6.setObjectName("label_cycle6")
        self.gridLayout.addWidget(self.label_cycle6, 6, 5, 1, 1)
        self.verticalLayout.addWidget(self.frame_center)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 87))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_bottom = QtWidgets.QLabel(self.frame_4)
        self.label_bottom.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_bottom.sizePolicy().hasHeightForWidth())
        self.label_bottom.setSizePolicy(sizePolicy)
        self.label_bottom.setMinimumSize(QtCore.QSize(0, 73))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        font.setPointSize(16)
        self.label_bottom.setFont(font)
        self.label_bottom.setText("")
        self.label_bottom.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_bottom.setObjectName("label_bottom")
        self.horizontalLayout_2.addWidget(self.label_bottom)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_bottom = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_bottom.sizePolicy().hasHeightForWidth())
        self.frame_bottom.setSizePolicy(sizePolicy)
        self.frame_bottom.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_bottom)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.frame_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(530, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_cal = QtWidgets.QPushButton(self.frame)
        self.pushButton_cal.setEnabled(False)
        self.pushButton_cal.setGeometry(QtCore.QRect(420, 7, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_cal.setFont(font)
        self.pushButton_cal.setObjectName("pushButton_cal")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(90, 10, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_top = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_top.setGeometry(QtCore.QRect(0, 0, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_top.setFont(font)
        self.lineEdit_top.setObjectName("lineEdit_top")
        self.lineEdit_bottom = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_bottom.setGeometry(QtCore.QRect(0, 30, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_bottom.setFont(font)
        self.lineEdit_bottom.setObjectName("lineEdit_bottom")
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_bottom)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(270, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_per = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_per.setEnabled(False)
        self.pushButton_per.setGeometry(QtCore.QRect(22, 7, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_per.setFont(font)
        self.pushButton_per.setObjectName("pushButton_per")
        self.pushButton_next = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_next.setEnabled(False)
        self.pushButton_next.setGeometry(QtCore.QRect(140, 7, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_next.setFont(font)
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_bottom)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.lineEdit_top.setInputMask('#99999999999999999999999999999999999999')
        self.lineEdit_bottom.setInputMask('#99999999999999999999999999999999999999')                               
        self.pushButton_next.clicked.connect(self.bottonClick_next)
        self.pushButton_cal.clicked.connect(self.botton_cal)
        self.pushButton_per.clicked.connect(self.bottonClick_per)
        self.comboBox.activated.connect(self.handleActivated_comboBox)
        self.num_combo = 0
        self.C = []
        self.A = []
        self.Q = []
        self.M = []
        self.state = []
        self.cycle = []
        self.num_next = 0
        self.pro = [self.C,self.A,self.Q,self.M,self.state,self.cycle]
        self.labelsum = [[self.label_c1,self.label_a1,self.label_q1,self.label_m1,self.label_state1,self.label_cycle1],
                         [self.label_c2,self.label_a2,self.label_q2,self.label_m2,self.label_state2,self.label_cycle2],
                         [self.label_c3,self.label_a3,self.label_q3,self.label_m3,self.label_state3,self.label_cycle3],
                         [self.label_c4,self.label_a4,self.label_q4,self.label_m4,self.label_state4,self.label_cycle4],
                         [self.label_c5,self.label_a5,self.label_q5,self.label_m5,self.label_state5,self.label_cycle5],
                         [self.label_c6,self.label_a6,self.label_q6,self.label_m6,self.label_state6,self.label_cycle6]]
        
    def bottonClick_next(self):
        self.pushButton_per.setEnabled(True)
        if self.num_next < len(self.C):
            self.num_next += 1
            self.set_label()
        if self.num_next == len(self.C):
            self.pushButton_next.setEnabled(False)
            
    def bottonClick_per(self):
        self.pushButton_next.setEnabled(True)
        if self.num_next > 0:
            self.num_next -= 1
            self.set_label()
        if self.num_next == 0:
            self.pushButton_per.setEnabled(False)
        if self.num_next <= 6:
            for i in range(self.num_next,6):
                for j in range(len(self.pro)):
                        self.labelsum[i][j].setStyleSheet("")
        
    def handleActivated_comboBox(self, index):
        self.num_combo = index
        if self.comboBox.itemText(index) != 'Select' :
            self.pushButton_cal.setEnabled(True)
        else:
            self.pushButton_cal.setEnabled(False)
            
    def setdefalut(self):
        self.C.clear()
        self.A.clear()
        self.Q.clear()
        self.M.clear()
        self.state.clear()
        self.cycle.clear()
        self.num_next = 0
        self.label_c.setHidden(False)
        for i in range(6):
            for j in range(6):
                if j <= 3:
                    self.labelsum[i][j].setText('0')
                else:
                    self.labelsum[i][j].setText('None')
                if j == 0:
                    self.labelsum[i][j].setHidden(False)
                self.labelsum[i][j].setStyleSheet('')
            
    def botton_cal(self):
        self.setdefalut()
        if self.comboBox.itemText(self.num_combo) == '(Multiplication)Unsigned Integer Multiplication' :
            if self.lineEdit_top.text()[0] != '-' and self.lineEdit_bottom.text()[0] != '-':
                self.unsigned_integer_cal()
            else:
                self.msgBox = QMessageBox()
                self.msgBox.setIcon(QMessageBox.Warning)
                self.msgBox.setText("Input Error\n Choose (+,+)")
                self.msgBox.setWindowTitle("Error")
                self.msgBox.show()
        elif self.comboBox.itemText(self.num_combo) == '(Multiplication)Booth’s Algorithm' :
            self.booth_algorithm_cal()
        elif self.comboBox.itemText(self.num_combo) == 'Division' :
            self.Division()
    
    def twos_comp(self,val, bits):
        if (val & (1 << (bits - 1))) != 0:
            val = val - (1 << bits)
        return val
    
    def Division(self):
        self.label_c.setHidden(True)
        self.label_a.setText('A')
        self.label_q.setText('Q')
        for i in range(6):
            for j in range(6):
                if j == 0:
                    self.labelsum[i][j].setHidden(True)
        
        m = self.lineEdit_bottom.text()
        q = self.lineEdit_top.text()
        m = bin(int(m))
        q = bin(int(q))
        numM = 0
        numQ = 0
        if m[0] == '-' :
            numM = 3
        else:
            numM = 2
        if q[0] == '-' :
            numQ = 3
        else:
            numQ = 2
        Max = max(len(m[numM:])+1,len(q[numQ:])+1)
        m = np.binary_repr(int(self.lineEdit_bottom.text()), Max)
        q = np.binary_repr(int(self.lineEdit_top.text()),Max)
        copym = m
        copyq = q
        a = ''
        if q[0] == '1' :
            for i in range(Max):
                a = '1' + a
        else:
            a = np.binary_repr(0,Max)
        count_dif = 0
        count = len(m)
        self.C.append('')
        self.A.append(a)
        self.Q.append(q)
        self.M.append(m)
        self.state.append('Initial Values')
        self.cycle.append(str(count_dif))
        while count != 0:
            count_dif += 1
            q = q + '0'
            a = a + q[0]
            q = q[1:]
            a = a[1:]
            self.C.append('')
            self.A.append(a)
            self.Q.append(q)
            self.M.append(m)
            self.state.append('Shift')
            self.cycle.append(str(count_dif))
            a = np.binary_repr(self.twos_comp(int(a,2),len(a)) - self.twos_comp(int(m,2),len(m)),Max)
            self.C.append('')
            self.A.append(a)
            self.Q.append('')
            self.M.append(m)
            self.state.append('Subtract')
            self.cycle.append(str(count_dif))
            if self.twos_comp(int(a,2),len(a)) < 0:
                q = q[:-1] + '0'
                a = np.binary_repr(self.twos_comp(int(a,2),len(a)) + self.twos_comp(int(m,2),len(m)),Max)
                self.C.append('')
                self.A.append(a)
                self.Q.append(q)
                self.M.append(m)
                self.state.append('Restore')
                self.cycle.append(str(count_dif))
            else:
                q = q[:-1] + '1'
                self.C.append('')
                self.A.append(a)
                self.Q.append(q)
                self.M.append(m)
                self.state.append('<html><head/><body><p>Set Q<span style=" vertical-align:sub;">0</span>=1</p></body></html>')
                self.cycle.append(str(count_dif))
            count -= 1

        ans1 = self.twos_comp(int(self.A[-1],2), len(self.A[-1]))
        ans2 = self.twos_comp(int(self.Q[-1],2), len(self.Q[-1]))
        self.label_bottom.setText(copyq + '(M) ÷ ' + copym + '(Q) = ' + self.Q[-1] + ' remainder = ' +self.A[-1] + '\n' + self.lineEdit_top.text() + ' ÷ ' + self.lineEdit_bottom.text()
        + ' = ' + str(ans2) + ' remainder = ' + str(ans1))
        self.pushButton_next.setEnabled(True)
        
    
    def booth_algorithm_cal(self):
        self.label_c.setText('A')
        self.label_a.setText('Q')
        self.label_q.setText('<html><head/><body><p>Q<span style=" vertical-align:sub;">-1</span></p></body></html>')
        m = self.lineEdit_top.text()
        q = self.lineEdit_bottom.text()
        m = bin(int(m))
        q = bin(int(q))
        numM = 0
        numQ = 0
        if m[0] == '-' :
            numM = 3
        else:
            numM = 2
        if q[0] == '-' :
            numQ = 3
        else:
            numQ = 2
        Max = max(len(m[numM:])+1,len(q[numQ:])+1)
        m = np.binary_repr(int(self.lineEdit_top.text()), Max)
        q = np.binary_repr(int(self.lineEdit_bottom.text()),Max)
        copym = m
        copyq = q
        a = np.binary_repr(0,Max)
        qm = '0'
        count_dif = 0
        count = len(m)
        self.C.append(a)
        self.A.append(q)
        self.Q.append(qm)
        self.M.append(m)
        self.state.append('Initial Values')
        self.cycle.append(str(count_dif))
        while count != 0:
            count_dif += 1
            if q[-1] == '1' and qm == '0' :
                a = np.binary_repr(self.twos_comp(int(a,2),len(a)) - self.twos_comp(int(m,2),len(m)),Max)
                self.C.append(a)
                self.A.append(q)
                self.Q.append(qm)
                self.M.append(m)
                self.state.append('A <- A-M')
                self.cycle.append(str(count_dif))
            elif q[-1] == '0' and qm == '1' :
                a = np.binary_repr(self.twos_comp(int(a,2),len(a)) + self.twos_comp(int(m,2),len(m)),Max)
                self.C.append(a)
                self.A.append(q)
                self.Q.append(qm)
                self.M.append(m)
                self.state.append('A <- A+M')
                self.cycle.append(str(count_dif))
            a = a[0] + a
            q = a[-1] + q
            qm = q[-1]
            a = a[:-1]
            q = q[:-1]
            self.C.append(a)
            self.A.append(q)
            self.Q.append(qm)
            self.M.append(m)
            self.state.append('Shift')
            self.cycle.append(str(count_dif))
            count -= 1
        
        
        ans = self.twos_comp(int(self.C[-1] + self.A[-1],2), len(self.C[-1])+len(self.A[-1]))
        self.label_bottom.setText(copym + '(M) x ' + copyq + '(Q) = ' + self.C[-1] + self.A[-1] + '\n' + self.lineEdit_top.text() + ' x ' + self.lineEdit_bottom.text()
        + ' = ' + str(ans))
        self.pushButton_next.setEnabled(True)
    
    
    def unsigned_integer_cal(self):
        self.label_c.setText('C')
        self.label_a.setText('A')
        self.label_q.setText('Q')
        m = self.lineEdit_top.text()
        q = self.lineEdit_bottom.text()
        m = bin(int(m))
        q = bin(int(q))
        m = m[2:]
        q = q[2:]
        copym = m
        copyq = q
        if len(m) > len(q):
            for i in range(len(m)-len(q)):
                q = '0' + q
        else:
            for j in range(len(q)-len(m)):
                m = '0' + m
        a = ''
        for o in range(len(q)):
            a = '0' + a
        c = '0'
        count_dif = 0
        self.C.append(c)
        self.A.append(a)
        self.Q.append(q)
        self.M.append(m)
        self.state.append('Initial Values')
        self.cycle.append(str(count_dif))
        count = len(q)
        while count != 0:
            count_dif += 1
            if q[-1] == '1' :
                a = bin(int(a,2)+int(m,2))
                a = a[2:]
                if len(m) > len(a):
                    for i in range(len(m)-len(a)):
                        a = '0' + a
                if len(a) > len(m):
                    c = a[0]
                    a = a[1:]
                self.C.append(c)
                self.A.append(a)
                self.Q.append(q)
                self.M.append(m)
                self.state.append('ADD')
                self.cycle.append(str(count_dif))
            a = c + a
            q = a[-1] + q
            a = a[:-1]
            q = q[:-1]
            c = '0'
            self.C.append(c)
            self.A.append(a)
            self.Q.append(q)
            self.M.append(m)
            self.state.append('Shift')
            self.cycle.append(str(count_dif))
            count -= 1
            
        ans = int(self.A[-1] + self.Q[-1],2)
        ans2 = ans
        ans = bin(ans)
        ans = ans[2:]
        self.label_bottom.setText(copym + '(M) x ' + copyq + '(Q) = ' + ans + '\n' + self.lineEdit_top.text() + ' x ' + self.lineEdit_bottom.text()
        + ' = ' + str(ans2))
        self.pushButton_next.setEnabled(True)
        
    
        
    def set_label(self):
        if self.num_next <= 6:
            for i in range(self.num_next):
                for j in range(len(self.pro)):
                    self.labelsum[i][j].setText(self.pro[j][i])
                    if self.num_next == len(self.C) and i+1 == len(self.C):
                        self.labelsum[i][j].setStyleSheet("background-color: rgb(29, 255, 85);")
                    elif self.num_next == i + 1:
                        self.labelsum[i][j].setStyleSheet("background-color: orange;")
                    else:
                        self.labelsum[i][j].setStyleSheet("")
                        
        else:
            for i in range(6):
                for j in range(len(self.pro)):
                    self.labelsum[i][j].setText(self.pro[j][i+(self.num_next-6)])
                    if self.num_next == len(self.C) and i + (self.num_next-6) + 1 == self.num_next:
                        self.labelsum[i][j].setStyleSheet("background-color: rgb(29, 255, 85);")
                    elif self.num_next == i + (self.num_next-6) + 1:
                        self.labelsum[i][j].setStyleSheet("background-color: orange;")
                    else:
                        self.labelsum[i][j].setStyleSheet("")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_top.setText(_translate("MainWindow", "HELLO!!!!"))
        self.label_c.setText(_translate("MainWindow", "None"))
        self.label_c5.setText(_translate("MainWindow", "0"))
        self.label_a4.setText(_translate("MainWindow", "0"))
        self.label_q5.setText(_translate("MainWindow", "0"))
        self.label_q4.setText(_translate("MainWindow", "0"))
        self.label_m2.setText(_translate("MainWindow", "0"))
        self.label_state1.setText(_translate("MainWindow", "None"))
        self.label_cycle1.setText(_translate("MainWindow", "None"))
        self.label_m5.setText(_translate("MainWindow", "0"))
        self.label_c4.setText(_translate("MainWindow", "0"))
        self.label_a1.setText(_translate("MainWindow", "0"))
        self.label_state4.setText(_translate("MainWindow", "None"))
        self.label_cycle4.setText(_translate("MainWindow", "None"))
        self.label_m1.setText(_translate("MainWindow", "0"))
        self.label_state3.setText(_translate("MainWindow", "None"))
        self.label_c2.setText(_translate("MainWindow", "0"))
        self.label_cycle3.setText(_translate("MainWindow", "None"))
        self.label_a2.setText(_translate("MainWindow", "0"))
        self.label_a3.setText(_translate("MainWindow", "0"))
        self.label_q3.setText(_translate("MainWindow", "0"))
        self.label_m3.setText(_translate("MainWindow", "0"))
        self.label_state5.setText(_translate("MainWindow", "None"))
        self.label_m.setText(_translate("MainWindow", "M"))
        self.label_cycle5.setText(_translate("MainWindow", "None"))
        self.label_q.setText(_translate("MainWindow", "None"))
        self.label_q1.setText(_translate("MainWindow", "0"))
        self.label_a5.setText(_translate("MainWindow", "0"))
        self.label_q2.setText(_translate("MainWindow", "0"))
        self.label_state.setText(_translate("MainWindow", "STATE"))
        self.label_m4.setText(_translate("MainWindow", "0"))
        self.label_c3.setText(_translate("MainWindow", "0"))
        self.label_state2.setText(_translate("MainWindow", "None"))
        self.label_a.setText(_translate("MainWindow", "None"))
        self.label_cycle.setText(_translate("MainWindow", "CYCLE"))
        self.label_c1.setText(_translate("MainWindow", "0"))
        self.label_cycle2.setText(_translate("MainWindow", "None"))
        self.label_c6.setText(_translate("MainWindow", "0"))
        self.label_a6.setText(_translate("MainWindow", "0"))
        self.label_q6.setText(_translate("MainWindow", "0"))
        self.label_m6.setText(_translate("MainWindow", "0"))
        self.label_state6.setText(_translate("MainWindow", "None"))
        self.label_cycle6.setText(_translate("MainWindow", "None"))
        self.pushButton_cal.setText(_translate("MainWindow", "calculate"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Select"))
        self.comboBox.setItemText(1, _translate("MainWindow", "(Multiplication)Unsigned Integer Multiplication"))
        self.comboBox.setItemText(2, _translate("MainWindow", "(Multiplication)Booth’s Algorithm"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Division"))
        self.pushButton_per.setText(_translate("MainWindow", "Pervious"))
        self.pushButton_next.setText(_translate("MainWindow", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

